"""empty message

Revision ID: 003f4b8045fc
Revises: 
Create Date: 2025-09-09 19:19:47.912855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003f4b8045fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services', sa.String(), nullable=True))
        batch_op.drop_column('service')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('services')

    # ### end Alembic commands ###
